notifications:
  email: false

language: c++
sudo: false

dist: focal

branches:
  only:
  - master
  
script:
  - cd test
  - make CXXFLAGS='-fprofile-arcs -ftest-coverage -g' LDFLAGS='-lgcov --coverage' test
  - ./test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
