notifications:
  email: false

language: c++
sudo: false

dist: focal

addons:
  apt:
    packages:
    - libboost-dev

branches:
  only:
  - master
  
script:
  - git clone https://github.com/boostorg/pfr
  - cd test
  - make CXXFLAGS='-fprofile-arcs -ftest-coverage -g' LDFLAGS='-lgcov --coverage' BOOST_PFR_PATH=../pfr/include test
  - ./test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
