notifications:
  email: false

language: c++
sudo: false

dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7

branches:
  only:
  - master
  
compiler:
  - clang

script:
  - cd test
  - make CXXFLAGS='-fprofile-arcs -ftest-coverage -g' test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
