name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcc-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev libboost-test-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Run test
      working-directory: test
      run: make test
      env:
        BOOST_PFR_PATH: ../pfr/include
        CXX: g++
        CXXFLAGS: '-fprofile-arcs -ftest-coverage -g'
        LDFLAGS: '-lgcov --coverage'
    - name: Codecov
      working-directory: test
      run: bash <(curl -s https://codecov.io/bash) -x "gcov"

  ubsan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev libboost-test-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Run test
      working-directory: test
      run: make test
      env:
        BOOST_PFR_PATH: ../pfr/include
        CXX: clang++
        CXXFLAGS: '-g -fsanitize=undefined'
        LDFLAGS: '-fsanitize=undefined -lgcc_s --rtlib=compiler-rt'

  asan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev libboost-test-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Run test
      working-directory: test
      run: make test
      env:
        BOOST_PFR_PATH: ../pfr/include
        CXX: clang++
        CXXFLAGS: '-fsanitize=address'
        LDFLAGS: '-fsanitize=address'

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Install Benchmark
      run: sudo apt-get install libbenchmark-dev
    - name: Make test
      working-directory: benchmark
      run: cmake -DBOOST_PFR_PATH=../pfr/include
      env:
        CC: gcc
        CXX: g++
    - name: Build and run test
      working-directory: benchmark
      run: make code && ./code
  
