name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Make test
      working-directory: test
      run: make CXXFLAGS='-fprofile-arcs -ftest-coverage -g' LDFLAGS='-lgcov --coverage' BOOST_PFR_PATH=../pfr/include test
    - name: Run test
      working-directory: test
      run: ./test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install libboost-dev
    - name: Get Boost PFR
      run: git clone https://github.com/boostorg/pfr
    - name: Make test
      working-directory: benchmark
      run: cmake . -G Ninja -DBOOST_PFR_PATH=../pfr/include
    - name: Build and run test
      run: ninja code && ./code
  
